name: CI/CD Pipeline - Frontend

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Este paso clona el repositorio

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat > ~/.ssh/config <<END
        Host target
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END

    - name: Install dependencies and build
      run: |
        cd beluar  
        npm install
        npm run build

    - name: Deploy to EC2
      run: |
        scp -r ./beluar/build/* target:/var/www/html/
        ssh target "sudo systemctl restart nginx"
